### ISSUE TITLE
HowTo convert string to bytes

### ISSUE THREAD

**Issue by Budlowski** [krakorj/phpmodbus#9]
Im trying to convert a string to bytes with a script like 
`$str = "String";

$arr = array();

for ( $pos=0; $pos < strlen($str); $pos ++ ) {

 $byte = substr($str, $pos);

 $arr[$pos] = ord($byte);

}

print_r($arr);
`

The output array looks like

> Array ( [0] => 83 [1] => 116 [2] => 114 [3] => 105 [4] => 110 [5] => 103 ) 

If i receive the same string from my Wago 750 it looks like 

> Array ( [0] => 83 [1] => 1 [2] => 114 [3] => 116 [4] => 110 [5] => 105 [6] => 0 [7] => 103 ) 

How do i get the bytes in the right order?

**Comment by krakorj** [comment]
Bytes are swapped due to the used endianness of WAGE PLC processor (https://en.wikipedia.org/wiki/Endianness). To convert the Wago 750 stream use `PhpType::bytes2string($bytes, $endianness = 0)`  i.e. the static function from https://github.com/krakorj/phpmodbus/blob/master/Phpmodbus/PhpType.php#L108

**Comment by Budlowski** [comment]
Thank you for your answer, but how to convert the string backwards to Bytes to send them to the PLC?

**Comment by krakorj** [comment]
This might be the answer, see https://stackoverflow.com/a/11466734

```
$byte_array = unpack('C*', 'The quick fox jumped over the lazy brown dog');
var_dump($byte_array);  // $byte_array should be int[] which can be converted
                        // to byte[] in C# since values are range of 0 - 255
```
